services:
  template-node-express-backend:
    build: 
      context: .
      target: development
    image: template-node-express-backend
    container_name: template-node-express-backend
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      POSTGRES_PASSWORD: ppp
      POSTGRES_PASSWORD_2: pppddd